# -*- coding: utf-8 -*-
"""Copy of prodigy_task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-IBn3kbxXW6-cYxhwa_Q_iH2A_7aHWng
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

data = pd.read_csv("population.csv")

data.head(266)

countries_to_plot = ['United States', 'Canada', 'Brazil', 'Japan', 'Germany', 'France','India']

#Filtering the data frame
filtered_data = data[data['Country Name'].isin(countries_to_plot)]

#Creating the bar chart
plt.bar (filtered_data['Country Name'], filtered_data['2022'])
plt.xlabel ('Country Name')
plt.ylabel ('Population in 2022')
plt.title('Population of selected countries in 2022')
plt.xticks(rotation=45, ha='right') #Rotating the x-axis labels for readability
plt.show()

import matplotlib.pyplot as plt

# Filtering the data frame
filtered_data = data[data['Country Name'].isin(countries_to_plot)]

# Transposing the dataframe to make years the index
filtered_data = filtered_data.set_index('Country Name').T

# Dropping non-year columns if any (keeping only numeric years)
filtered_data = filtered_data.iloc[1:].apply(pd.to_numeric, errors='coerce')

# Plotting histogram of population data
plt.figure(figsize=(10, 5))
plt.hist(filtered_data.values.flatten(), bins=20, edgecolor='black', alpha=0.7)

plt.xlabel('Population')
plt.ylabel('Frequency')
plt.title('Histogram of Population Data for Selected Countries')
plt.grid()
plt.show()

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

# Loading the dataset
data = pd.read_csv('population.csv')

# Transposing the dataframe to make years the index
data = data.set_index('Country Name').T

# Dropping non-year columns if any (keeping only numeric years)
data = data.iloc[1:].apply(pd.to_numeric, errors='coerce')

# Flattening the data
hist_data = data.values.flatten()

# Plotting histogram of population data
plt.figure(figsize=(12, 6))
plt.hist(hist_data, bins=30, alpha=0.5, edgecolor='black')

plt.xlabel('Population')
plt.ylabel('Frequency')
plt.title('Histogram of Population Data')
plt.grid()
plt.show()

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

# Loading the dataset
data = pd.read_csv('population.csv')

# Selecting the latest available year
latest_year = data.columns[-1]

# Sorting data for better visualization
data = data.sort_values(by=latest_year, ascending=False)

# Selecting top 10 countries with highest population
top_countries = data.head(10)

# Plotting bar chart of population data
plt.figure(figsize=(12, 6))
plt.bar(top_countries['Country Name'], top_countries[latest_year], color='skyblue', edgecolor='black')

plt.xlabel('Country')
plt.ylabel('Population')
plt.title(f'Population of Top 10 Countries in {latest_year}')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y')
plt.show()